parameters:
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'
    GOOGLE_BOOKS_API: '%env(GOOGLE_BOOKS_API)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Injection correcte de la clé API
    App\Controller\BookController:
        arguments:
            $googleBooksApiKey: '%env(resolve:GOOGLE_BOOKS_API)%'
